# Generated by Django 3.2.8 on 2021-10-17 20:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер машини')),
                ('tank_volume', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Литраж бака')),
                ('type_of_car', models.CharField(max_length=100, verbose_name='Тип машины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Отчество')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заправки')),
                ('adress', models.CharField(max_length=300, verbose_name='Адресс заправки')),
                ('capacity_gas_station', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Общий обьём заправки')),
                ('total_fuel', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Топлива на заправке в данный момент')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗС',
            },
        ),
        migrations.CreateModel(
            name='FuelStationRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_volume', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Было заправлено')),
                ('date_of_refill', models.DateTimeField(auto_now=True, verbose_name='Дата и время заправки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.fuelstation', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Пополнение АЗС топливом',
                'verbose_name_plural': 'Пополнение АЗС топливом',
                'ordering': ['date_of_refill'],
            },
        ),
        migrations.CreateModel(
            name='CarRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillin_volume', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Было заправлено')),
                ('date_of_fuel', models.DateTimeField(auto_now=True, verbose_name='Дата и время заправки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.cars', verbose_name='Машина')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.drivers', verbose_name='Водитель')),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.fuelstation', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Запрвка',
                'ordering': ['date_of_fuel'],
            },
        ),
    ]
