# Generated by Django 3.2.8 on 2021-10-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_autoparts_contactor_status_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='type_of_car',
            field=models.CharField(max_length=127, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='patronymic',
            field=models.CharField(max_length=127, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='surname',
            field=models.CharField(max_length=127, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='patronymic',
            field=models.CharField(max_length=127, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='surname',
            field=models.CharField(max_length=127, verbose_name='Отчество'),
        ),
    ]
