# Generated by Django 3.2.8 on 2021-10-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20211017_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autopart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('invent_number', models.CharField(max_length=127, verbose_name='Инвентарный номер')),
                ('number', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Цена')),
                ('car_for_using', models.CharField(max_length=255, verbose_name='Техника для использования')),
                ('date_of_supply', models.DateField(verbose_name='Дата поступления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('return_detail', models.BooleanField(verbose_name='Возвращено')),
                ('accepr_from_top', models.BooleanField(verbose_name='Подтверждение свыше')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.AlterModelOptions(
            name='contactor',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.DeleteModel(
            name='Autoparts',
        ),
        migrations.AddField(
            model_name='autopart',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.contactor', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='autopart',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='autopart',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.warehouse', verbose_name='Склад'),
        ),
    ]
