# Generated by Django 3.2.8 on 2021-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20211017_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='date_of_supply',
            field=models.DateField(auto_now=True, verbose_name='Дата поступления'),
        ),
    ]
