# Generated by Django 3.2.8 on 2021-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_status_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(default='0', max_length=127),
        ),
    ]
