# Generated by Django 3.2.8 on 2021-10-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_status_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(default='0', max_length=127, unique=True),
        ),
    ]
