# Generated by Django 3.2.8 on 2021-10-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20211018_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='accepr_from_top',
            field=models.BooleanField(default=False, verbose_name='Подтверждение свыше'),
        ),
        migrations.AlterField(
            model_name='autopart',
            name='return_detail',
            field=models.BooleanField(default=False, verbose_name='Возвращено'),
        ),
        migrations.AlterField(
            model_name='autopart',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.status', verbose_name='Статус'),
        ),
    ]
