# Generated by Django 3.2.8 on 2021-10-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_status_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
