# Generated by Django 3.2.8 on 2021-10-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_autopart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='На складе', max_length=127),
        ),
    ]
